name: hyper_supabase
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.0.4
  uuid: ^4.0.0
  cached_network_image: ^3.3.1
  permission_handler: ^11.2.0
  geolocator: ^13.0.1
  flutter_map: ^7.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6
  blur: ^4.0.0
  flutter_svg: ^2.0.5 
  custom_clippers: ^2.0.0
  flutter_markdown: ^0.7.1
  faker_dart: ^0.2.1
  # Versi terbaru bermasalah
  # syncfusion_flutter_charts: ^26.2.8
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  flutter_animate: ^4.1.1+1
  dio: ^5.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.1
  screenshot: ^3.0.0
  syncfusion_flutter_calendar: ^28.1.37
  google_maps_flutter: ^2.6.0
  dio_http2_adapter: ^2.5.2
  # supabase_flutter: ^2.6.0
  youtube_player_flutter: ^9.1.1
  syncfusion_flutter_charts: ^28.1.37
  alarm: ^4.0.3
  audioplayers: ^6.1.0
  vibration: ^2.0.1
  flutter_bluetooth_printer: ^2.17.1
  flutter_tts: ^4.2.0
  widgets_to_image: ^1.0.0
  speech_to_text: ^7.0.0
  get_it: ^8.0.2
  auto_route: ^9.2.2
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  mock_supabase_http_client: ^0.0.3+1
  supabase: ^2.6.1
  connectivity_plus: ^6.1.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  app_links: ^6.3.3
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.2
  mockito: ^5.4.4
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/music/
